presubmits:
  openenclave/oeedger8r-cpp:
  - name: pr-openenclave-oeedger8r-cpp-ubuntu1604-Release-c-8
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu1604:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=Release --compiler=clang-8'

  - name: pr-openenclave-oeedger8r-cpp-ubuntu1604-Release-c-7
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu1604:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=Release --compiler=clang-7'

  - name: pr-openenclave-oeedger8r-cpp-ubuntu1604-Release-gcc
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu1604:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=Release --compiler=gcc'

  - name: pr-openenclave-oeedger8r-cpp-ubuntu1604-Debug-c-8
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu1604:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=Debug --compiler=clang-8'

  - name: pr-openenclave-oeedger8r-cpp-ubuntu1604-Debug-c-7
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu1604:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=Debug --compiler=clang-7'

  - name: pr-openenclave-oeedger8r-cpp-ubuntu1604-Debug-gcc
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu1604:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=Debug --compiler=gcc'

  - name: pr-openenclave-oeedger8r-cpp-ubuntu1804-Release-c-8
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu1804:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=Release --compiler=clang-8'

  - name: pr-openenclave-oeedger8r-cpp-ubuntu1804-Release-c-7
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu1804:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=Release --compiler=clang-7'

  - name: pr-openenclave-oeedger8r-cpp-ubuntu1804-Release-gcc
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu1804:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=Release --compiler=gcc'

  - name: pr-openenclave-oeedger8r-cpp-ubuntu1804-Debug-c-8
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu1804:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=Debug --compiler=clang-8'

  - name: pr-openenclave-oeedger8r-cpp-ubuntu1804-Debug-c-7
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu1804:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=Debug --compiler=clang-7'

  - name: pr-openenclave-oeedger8r-cpp-ubuntu1804-Debug-gcc
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu1804:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=Debug --compiler=gcc'        

  - name: pr-openenclave-oeedger8r-cpp-jenk
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
          - /bin/bash
          args:
          - -c
          - "python /hack/jenkins_bootstrap.py --job openenclave-oeedger8r-cpp-jenkins-full --jenkins-user $(echo $JENKINS_USER) --url $(echo $JENKINS_URL) --jenkins-password $(echo $JENKINS_TOKEN)"
