postsubmits:
  openenclave-ci/oeedger8r-cpp:
  - name: post-openenclave-ci-oeedger8r-cpp-ubuntu1604-Release-c-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=clang-8'

  - name: post-openenclave-ci-oeedger8r-cpp-ubuntu1604-Release-c-7
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=clang-7'

  - name: post-openenclave-ci-oeedger8r-cpp-ubuntu1604-Release-gcc
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=gcc'
  
  - name: post-openenclave-ci-oeedger8r-cpp-ubuntu1604-Debug-c-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=clang-8'
       
  - name: post-openenclave-ci-oeedger8r-cpp-ubuntu1604-Debug-c-7
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=clang-7'
      
  - name: post-openenclave-ci-oeedger8r-cpp-ubuntu1604-Debug-gcc
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=gcc'
       
  - name: post-openenclave-ci-oeedger8r-cpp-ubuntu1804-Release-c-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=clang-8'
      
  - name: post-openenclave-ci-oeedger8r-cpp-ubuntu1804-Release-c-7
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=clang-7'
      
  - name: post-openenclave-ci-oeedger8r-cpp-ubuntu1804-Release-gcc
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=gcc'

  - name: post-openenclave-ci-oeedger8r-cpp-ubuntu1804-Debug-c-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=clang-8'
       
  - name: post-openenclave-ci-oeedger8r-cpp-ubuntu1804-Debug-c-7
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=clang-7'
      
  - name: post-openenclave-ci-oeedger8r-cpp-ubuntu1804-Debug-gcc
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=gcc'

  - name: post-openenclave-ci-oeedger8r-cpp-jenk
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - '-c'
            - "python /hack/jenkins_bootstrap.py --job openenclave-oeedger8r-cpp-jenkins-full --jenkins-user $(echo $JENKINS_USER) --url $(echo $JENKINS_URL) --jenkins-password $(echo $JENKINS_TOKEN)"
