prowjob_namespace: default
pod_namespace: test-pods
log_level: debug
tide:
  sync_period: 1m
  queries:
    - orgs:
        - openenclave
      labels:
        - lgtm
        - approved
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - needs-rebases
  merge_method:
    openenclave-ci/openenclave: merge
    openenclave/test-infra: merge
    openenclave/oeedger8r: merge
  blocker_label: tide/merge-blocker
  squash_label: tide/merge-method-squash
  rebase_label: tide/merge-method-rebase
  merge_label: tide/merge-method-merge
plank:
  job_url_prefix_config:
    '*': 'https://oe-prow-status.westus2.cloudapp.azure.com/view/gcs/'
  job_url_template: 'https://oe-prow-status.westus2.cloudapp.azure.com/view/gcs/{{if eq .Spec.Type "presubmit"}}pr-logs/pull{{else if eq .Spec.Type "batch"}}pr-logs/pull{{else}}logs{{end}}{{if eq .Spec.Type "presubmit"}}/{{.Spec.Refs.Org}}_{{.Spec.Refs.Repo}}/{{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}{{else if eq .Spec.Type "batch"}}/batch{{end}}/{{.Spec.Job}}/{{.Status.BuildID}}/'
  report_templates:
    '*': '[Full PR test history](https://oe-prow-status.westus2.cloudapp.azure.com/pr-history?org={{.Spec.Refs.Org}}&repo={{.Spec.Refs.Repo}}&pr={{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}). [Your PR dashboard](https://oe-prow-status.westus2.cloudapp.azure.com/pr?query=is%3Apr%20state%3Aopen%20author%3{{with index .Spec.Refs.Pulls 0}}{{.Author}}{{end}}). Please help us cut down on flakes by opening an issue when you hit one in your PR.'
  pod_pending_timeout: 1h
  pod_unscheduled_timeout: 1h
  default_decoration_configs:
    '*':
      timeout: 2h
      grace_period: 30m
      utility_images:
        clonerefs: "gcr.io/k8s-prow/clonerefs:v20200710-7fa016752a"
        initupload: "gcr.io/k8s-prow/initupload:v20200710-7fa016752a"
        entrypoint: "gcr.io/k8s-prow/entrypoint:v20200710-7fa016752a"
        sidecar: "gcr.io/k8s-prow/sidecar:v20200710-7fa016752a"
      gcs_configuration:
        bucket: oe-prow-artifacts
        path_strategy: explicit
      gcs_credentials_secret: gcs-credentials
      resources:
        clonerefs:
          requests:
            cpu: 100m
        initupload:
          requests:
            cpu: 100m
        place_entrypoint:
          requests:
            cpu: 100m
        sidecar:
          requests:
            cpu: 100m
github_reporter:
  job_types_to_report:
    - presubmit
    - postsubmit
sinker:
  resync_period: 1m
  max_prowjob_age: 48h
  max_pod_age: 48h
  terminated_pod_ttl: 30m
slack_reporter_configs:
  # Wildcard (i.e. catch-all) slack config
  "*":
    job_types_to_report:
      - postsubmit
      - periodic
      - batch
    job_states_to_report:
      - failure
      - error
    channel: test-failures
    # The template shown below is the default
    report_template: "Job {{.Spec.Job}} of type {{.Spec.Type}} ended with state {{.Status.State}}. <{{.Status.URL}}|View logs>"

deck:
  # Branding of the frontend
  branding:
      # BackgroundColor is the color of the background.
      background_color: 'white'
      header_color: 'DodgerBlue'
      logo: 'https://openenclave.io/assets/images/OpenEnclave.png'

  # HiddenRepos is a list of orgs and/or repos that should not be displayed by Deck.
  hidden_repos:

  spyglass:
    size_limit: 100000000  # 100 MB
    lenses:
    - lens:
        name: metadata
      required_files:
      - ^(?:started|finished)\.json$
      optional_files:
      - ^(?:podinfo|prowjob)\.json$
    - lens:
        name: buildlog
        config:
          highlight_regexes:
          - timed out
          - 'ERROR:'
          - (FAIL|Failure \[)\b
          - panic\b
          - ^E\d{4} \d\d:\d\d:\d\d\.\d\d\d]
          # Gateway Issues
          - Your build somehow failed
          - 502 Bad Gateway
          - 504 Gateway Time-out
          - nginx
          # Info
          - Job URL
      required_files:
      - ^build-log\.txt$
    - lens:
        name: junit
      required_files:
      - ^artifacts/junit.*\.xml$
    - lens:
        name: podinfo
      required_files:
        - ^podinfo\.json$
presets:
- env:
  - name: JENKINS_TOKEN
    valueFrom:
      secretKeyRef:
        name: jenkins-token
        key: jenkins-token

  - name: JENKINS_USER
    value: build_runner
  
  - name: JENKINS_URL
    value: https://openenclave-jenkins.eastus.cloudapp.azure.com
