periodics:

  - name: ci-openenclave-ping
    extra_refs:
    - org: openenclave
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 60m
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/ping --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=master"        

  - name: ci-openenclave-Rhel8BuildClang-8
    extra_refs:
    - org: openenclave
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 60m
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Rhel8BuildClang-8 --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=master"        

  - name: ci-openenclave-Rhel8BuildGCC
    extra_refs:
    - org: openenclave
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 60m
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Rhel8BuildGCC --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=master"        

  - name: ci-openenclave-Ubuntu1604DebugClang-7
    extra_refs:
    - org: openenclave
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 60m
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Ubuntu1604DebugClang-7 --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=master"        

  - name: ci-openenclave-Ubuntu1604ReleaseClang-7
    extra_refs:
    - org: openenclave
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 60m
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Ubuntu1604ReleaseClang-7 --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=master"        

  - name: ci-openenclave-Ubuntu1604RelWithDebInfoClang-7
    extra_refs:
    - org: openenclave
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 60m
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Ubuntu1604RelWithDebInfoClang-7 --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=master"        

  - name: ci-openenclave-Ubuntu1804BuildGCC
    extra_refs:
    - org: openenclave
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 60m
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Ubuntu1804BuildGCC --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=master"        

  - name: ci-openenclave-Ubuntu1804DebugClang-7
    extra_refs:
    - org: openenclave
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 60m
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Ubuntu1804DebugClang-7 --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=master"        

  - name: ci-openenclave-Ubuntu1804ReleaseClang-7
    extra_refs:
    - org: openenclave
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 60m
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Ubuntu1804ReleaseClang-7 --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=master"        

  - name: ci-openenclave-Ubuntu1804RelWithDebInfoClang-7
    extra_refs:
    - org: openenclave
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 60m
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Ubuntu1804RelWithDebInfoClang-7 --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=master"        

  - name: ci-openenclave-Ubuntu1804BuildGCC
    extra_refs:
    - org: openenclave
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 60m
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Ubuntu1804BuildGCC --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=master"        

  - name: ci-openenclave-Windows2016BuildRel
    extra_refs:
    - org: openenclave
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 60m
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Windows2016BuildRel --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=master"        

  - name: ci-openenclave-Windows2016BuildDebug
    extra_refs:
    - org: openenclave
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 60m
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Windows2016BuildDebug --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=master"        

  - name: ci-openenclave-Windows2019BuildRel
    extra_refs:
    - org: openenclave
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 60m
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Windows2019BuildRel --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=master"        

  - name: ci-openenclave-Windows2019BuildDebug
    extra_refs:
    - org: openenclave
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 60m
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Windows2019BuildDebug --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=master"        
