---
controller:
  stats:
    enabled: true
  metrics:
    enabled: true
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 85
  nodeSelector:
    role: ingress
  podLabels:
    app: ingress-nginx
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - ingress-nginx
        topologyKey: "kubernetes.io/hostname"
