---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-master-nodeport
  labels:
    app: jenkins-master
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: slave
    port: 50000
    targetPort: 50000
    protocol: TCP
  selector:
    app: jenkins-master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-master
spec:
  selector:
    matchLabels:
      app: jenkins-master
  template:
    metadata:
      labels:
        app: jenkins-master
    spec:
      containers:
      - name: jenkins-mastens-plugin-clir
        image: jenkins/jenkins:2.263.3-lts
        imagePullPolicy: Always
        env:
        - name: JAVA_OPTS
          value: -Djenkins.install.runSetupWizard=false -Xmx2048M
        - name: CASC_JENKINS_CONFIG
          value: /var/jenkins_home/configuration/
        volumeMounts:
        - name: plugins
          mountPath: "/plugins"
          readOnly: true
        - name: jenkins-home
          mountPath: "/var/jenkins_home/"
        - name: jenkins-master-configuration
          mountPath: "/var/jenkins_home/configuration"
        livenessProbe:
          httpGet:
            path: /login
            port: 8080
          failureThreshold: 10
          initialDelaySeconds: 1800
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        startupProbe:
          httpGet:
            path: /login
            port: 8080
          failureThreshold: 60
          periodSeconds: 30
        resources:
          requests:
            cpu: "4"
            memory: 8Gi
          limits:
            cpu: "8"
            memory: 30Gi
      initContainers:
      - name: plugin-install
        image: jenkins/jenkins:2.263.3-lts
        imagePullPolicy: Always
        volumeMounts:
        - name: plugins
          mountPath: "plugins"
          readOnly: true
        - name: jenkins-home
          mountPath: "/var/jenkins_home/"
          command: ["/bin/jenkins-plugin-cli", "--plugin-file", "/plugins/plugins.txt", "--plugin-download-directory", "/var/jenkins_home/plugins"]
      volumes:
      - name: plugins
        configMap:
          name: plugins
          items:
            - key: "plugins.txt"
              path: "plugins.txt"
      - name: jenkins-home
        emptyDir: {}
      - name: jenkins-master-configuration
        persistentVolumeClaim:
          claimName: jenkins-master-configuration
